"use client";

import { useEffect, useState } from "react";
import { Download, FileText, LoaderCircle, ShieldAlert } from "lucide-react";

import type { RepositoryDocumentation, RiskFinding, RiskSeverity } from "@/types/repository";

const severityStyles: Record<RiskSeverity, string> = { critical: "border-red-500/30 bg-red-500/10 text-red-200", high: "border-orange-400/30 bg-orange-400/10 text-orange-200", medium: "border-amber-400/30 bg-amber-400/10 text-amber-200", low: "border-sky-400/30 bg-sky-400/10 text-sky-200" };
const docs: Array<{ key: keyof RepositoryDocumentation; label: string; filename: string }> = [{ key: "readme", label: "README", filename: "README.md" }, { key: "architecture", label: "Architecture", filename: "ARCHITECTURE.md" }, { key: "folders", label: "Folders", filename: "FOLDERS.md" }, { key: "api", label: "API", filename: "API.md" }];

export function RiskAnalyzer({ repositoryId }: { repositoryId: string }) {
  const [findings, setFindings] = useState<RiskFinding[]>([]); const [documentation, setDocumentation] = useState<RepositoryDocumentation | null>(null); const [loading, setLoading] = useState(true); const [selectedDoc, setSelectedDoc] = useState<keyof RepositoryDocumentation>("readme");
  useEffect(() => { fetch(`/api/repositories/${repositoryId}/risks`).then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then((data) => { setFindings(data.risks); setDocumentation(data.documentation); }).catch(() => undefined).finally(() => setLoading(false)); }, [repositoryId]);
  function download() { if (!documentation) return; const item = docs.find((doc) => doc.key === selectedDoc)!; const url = URL.createObjectURL(new Blob([documentation[selectedDoc]], { type: "text/markdown" })); const link = document.createElement("a"); link.href = url; link.download = item.filename; link.click(); URL.revokeObjectURL(url); }
  if (loading) return <div className="grid min-h-80 place-items-center rounded-2xl border border-white/[.08] bg-zinc-900/50"><LoaderCircle className="size-5 animate-spin text-violet-400"/></div>;
  const high = findings.filter((finding) => finding.severity === "critical" || finding.severity === "high").length;
  return <section className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border border-white/[.08] bg-zinc-900/50 p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.14em] text-violet-400">REPOSITORY HEALTH</p><h2 className="mt-2 text-xl font-semibold text-white">Risks, prioritized.</h2></div><div className="rounded-xl border border-white/[.08] bg-zinc-950 px-3 py-2 text-center"><p className="text-lg font-semibold text-white">{findings.length}</p><p className="text-[10px] text-zinc-500">findings</p></div></div><div className="mt-5 grid grid-cols-3 gap-2"><HealthStat label="High risk" value={high}/><HealthStat label="Circular" value={findings.filter((finding) => finding.title.includes("Circular")).length}/><HealthStat label="Quality" value={Math.max(0, 100 - high * 10 - findings.length * 2)}/></div><div className="mt-5 max-h-[420px] space-y-2 overflow-auto pr-1">{findings.length ? findings.map((finding) => <article key={finding.id} className="rounded-xl border border-white/[.07] bg-zinc-950/50 p-3"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-medium text-zinc-100">{finding.title}</h3><span className={`rounded-full border px-2 py-0.5 text-[10px] font-medium capitalize ${severityStyles[finding.severity]}`}>{finding.severity}</span></div><p className="mt-1.5 text-xs leading-5 text-zinc-400">{finding.description}</p><p className="mt-2 text-xs text-violet-200">{finding.recommendation}</p>{finding.files.map((file) => <p key={file} className="mt-2 truncate font-mono text-[10px] text-zinc-600">{file}</p>)}</article>) : <div className="py-16 text-center"><ShieldAlert className="mx-auto size-6 text-emerald-400"/><p className="mt-3 text-sm text-zinc-400">No heuristic risks were detected.</p></div>}</div></div><div className="overflow-hidden rounded-2xl border border-white/[.08] bg-zinc-900/50"><div className="flex flex-wrap items-center gap-2 border-b border-white/[.06] p-3">{docs.map((doc) => <button key={doc.key} onClick={() => setSelectedDoc(doc.key)} className={`rounded-lg px-3 py-2 text-xs transition ${selectedDoc === doc.key ? "bg-white/[.08] text-white" : "text-zinc-500 hover:text-zinc-300"}`}>{doc.label}</button>)}<button onClick={download} className="ml-auto inline-flex items-center gap-1.5 rounded-lg border border-white/[.08] px-3 py-2 text-xs text-zinc-300 hover:bg-white/[.05]"><Download className="size-3.5"/> Export</button></div><div className="p-5"><p className="mb-3 flex items-center gap-2 text-xs font-medium text-zinc-500"><FileText className="size-3.5"/> Generated Markdown</p><pre className="h-[510px] overflow-auto whitespace-pre-wrap rounded-xl bg-zinc-950 p-4 font-mono text-xs leading-6 text-zinc-300">{documentation?.[selectedDoc] ?? "Documentation unavailable."}</pre></div></div></section>;
}
function HealthStat({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-white/[.06] bg-zinc-950/70 p-3"><p className="text-lg font-semibold text-white">{value}{label === "Quality" ? "/100" : ""}</p><p className="mt-1 text-[10px] text-zinc-500">{label}</p></div>; }
