"use client";

import { motion } from "framer-motion";
import { ArrowRight, Boxes, BrainCircuit, Check, ChevronDown, CirclePlay, GitBranch, Github, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { ImportRepositoryDialog } from "@/features/repository-import/components/import-repository-dialog";

const features = [{ icon: BrainCircuit, title: "Instant engineering context", body: "Ask the questions a senior engineer would ask and get grounded answers in seconds." }, { icon: GitBranch, title: "Architecture that stays clear", body: "See the systems, boundaries, and dependencies that make your repository tick." }, { icon: ShieldCheck, title: "Know the blast radius", body: "Understand what a change touches before it becomes a surprise in production." }];
const testimonials = [{ quote: "GitLens gave our new engineer the context usually locked in months of Slack history.", name: "Maya Chen", role: "VP Engineering, Orbital" }, { quote: "The first tool that made a 400k-line codebase feel genuinely approachable.", name: "Alex Rivera", role: "Staff Engineer, Northstar" }, { quote: "It feels like code review from the teammate who knows every decision behind the repo.", name: "Priya Shah", role: "Founder, Pinwheel" }];
const faqs = [{ question: "What kinds of repositories can I import?", answer: "You can import public GitHub repositories with a URL or upload a ZIP archive up to 50 MB. GitLens validates the repository structure before preparing it." }, { question: "Does GitLens change my repository?", answer: "No. GitLens only reads a shallow, temporary copy of public GitHub repositories. It never writes to your source code." }, { question: "Can I use it before connecting GitHub?", answer: "Yes. Upload a ZIP of your repository to explore the same import flow without connecting an account." }];

const reveal = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } };

export function LandingPage() {
  return <main className="overflow-hidden bg-zinc-950"><div className="pointer-events-none absolute inset-x-0 top-0 h-[700px] bg-[radial-gradient(ellipse_70%_45%_at_50%_0%,rgba(124,58,237,.25),transparent)]" />
    <Nav />
    <section className="relative mx-auto max-w-7xl px-5 pb-24 pt-20 text-center sm:px-8 sm:pt-28 lg:pb-32"><motion.div initial="hidden" animate="visible" variants={reveal} transition={{ duration: .45 }} className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-1.5 text-xs font-medium text-violet-200"><Sparkles className="size-3.5" /> Repository intelligence for ambitious teams</motion.div><motion.h1 initial="hidden" animate="visible" variants={reveal} transition={{ delay: .08, duration: .55 }} className="mx-auto mt-7 max-w-5xl text-balance text-5xl font-semibold tracking-[-.055em] text-white sm:text-6xl lg:text-7xl">The fastest way to understand code you didn’t write.</motion.h1><motion.p initial="hidden" animate="visible" variants={reveal} transition={{ delay: .16 }} className="mx-auto mt-7 max-w-2xl text-pretty text-base leading-7 text-zinc-400 sm:text-lg">GitLens AI turns any repository into an interactive map of its architecture, intent, and risk—so your team can build with confidence from day one.</motion.p><motion.div initial="hidden" animate="visible" variants={reveal} transition={{ delay: .24 }} className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"><ImportRepositoryDialog /><Button asChild size="lg" variant="outline" className="w-full sm:w-auto"><a href="#demo"><CirclePlay className="size-4" /> Watch demo</a></Button></motion.div><p className="mt-5 flex items-center justify-center gap-1.5 text-xs text-zinc-500"><Check className="size-3.5 text-emerald-400" /> Start with any public repository</p><HeroPreview /></section>
    <SectionIntro eyebrow="ONE REPOSITORY. COMPLETE CLARITY." title="Context is a superpower." description="Stop hunting through folders, tickets, and tribal knowledge. GitLens gives every engineer a shared mental model of the system." /><section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8 sm:pb-32"><div className="grid gap-4 md:grid-cols-3">{features.map((feature, index) => <motion.article key={feature.title} initial="hidden" whileInView="visible" viewport={{ once: true }} variants={reveal} transition={{ delay: index * .08 }} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-6"><div className="grid size-10 place-items-center rounded-xl bg-violet-400/10 text-violet-300"><feature.icon className="size-5" /></div><h3 className="mt-5 text-base font-medium text-white">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">{feature.body}</p></motion.article>)}</div></section>
    <ArchitecturePreview />
    <DemoPreview />
    <section className="border-y border-white/[.06] bg-white/[.015] py-24 sm:py-32"><SectionIntro eyebrow="LOVED BY TEAMS WHO SHIP" title="The clarity compound effect." description="When the whole team shares context, every decision gets better." /><div className="mx-auto mt-14 grid max-w-7xl gap-4 px-5 sm:px-8 md:grid-cols-3">{testimonials.map(({ quote, name, role }) => <article key={name} className="rounded-2xl border border-white/[.08] bg-zinc-900/50 p-6"><p className="text-base leading-7 text-zinc-200">“{quote}”</p><div className="mt-7"><p className="text-sm font-medium text-white">{name}</p><p className="mt-1 text-xs text-zinc-500">{role}</p></div></article>)}</div></section>
    <Faq />
    <section className="mx-auto max-w-4xl px-5 py-24 text-center sm:px-8 sm:py-32"><div className="rounded-3xl border border-violet-400/20 bg-[radial-gradient(ellipse_at_top,rgba(124,58,237,.18),transparent_70%)] px-6 py-14 sm:px-12"><Github className="mx-auto size-7 text-zinc-300" /><h2 className="mt-5 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Your codebase has a story.</h2><p className="mx-auto mt-4 max-w-xl text-zinc-400">Make it easy for every engineer to understand it.</p><div className="mt-8 flex justify-center"><ImportRepositoryDialog /></div></div></section>
    <Footer />
  </main>;
}

function Nav() { return <nav className="relative mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#top" className="flex items-center gap-2 font-semibold tracking-tight text-white"><span className="grid size-8 place-items-center rounded-lg bg-gradient-to-br from-violet-400 to-indigo-600"><GitBranch className="size-4" /></span>GitLens <span className="text-violet-400">AI</span></a><div className="hidden items-center gap-6 text-sm text-zinc-400 md:flex"><a href="#features" className="hover:text-white">Product</a><a href="#architecture" className="hover:text-white">Architecture</a><a href="#faq" className="hover:text-white">FAQ</a></div><ImportRepositoryDialog /></nav>; }
function HeroPreview() { return <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .35, duration: .65 }} className="relative mx-auto mt-16 max-w-5xl rounded-2xl border border-white/10 bg-zinc-900/70 p-2 shadow-glow"><div className="overflow-hidden rounded-xl border border-white/[.06] bg-[#111113] text-left"><div className="flex h-11 items-center gap-2 border-b border-white/[.06] px-4"><i className="size-2.5 rounded-full bg-red-400/70"/><i className="size-2.5 rounded-full bg-amber-400/70"/><i className="size-2.5 rounded-full bg-emerald-400/70"/><span className="ml-3 text-xs text-zinc-500">northstar / platform</span></div><div className="grid min-h-[280px] sm:grid-cols-[180px_1fr]"><aside className="hidden border-r border-white/[.06] p-4 sm:block"><p className="mb-3 text-[10px] font-semibold uppercase tracking-widest text-zinc-600">Repository</p>{["app", "components", "features", "services"].map((item) => <p key={item} className="mb-2 flex gap-2 text-xs text-zinc-400"><span className="size-1.5 rounded-sm bg-violet-400"/>{item}</p>)}</aside><div className="p-6 sm:p-8"><p className="flex items-center gap-2 text-xs text-violet-300"><Sparkles className="size-4"/> GitLens overview</p><h2 className="mt-5 text-xl font-medium text-white">The platform, explained.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-400">A modular Next.js application with a clear boundary between the dashboard, repository processing, and AI services.</p><div className="mt-7 flex flex-wrap gap-2">{["12 modules", "34 dependencies", "2 risks surfaced"].map((item) => <span key={item} className="rounded-md border border-white/10 bg-white/[.03] px-2.5 py-1 text-xs text-zinc-400">{item}</span>)}</div></div></div></div></motion.div>; }
function SectionIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div id="features" className="mx-auto max-w-2xl px-5 pb-14 pt-24 text-center sm:px-8 sm:pt-32"><p className="text-xs font-semibold tracking-[.16em] text-violet-400">{eyebrow}</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-4xl">{title}</h2><p className="mt-4 text-zinc-400">{description}</p></div>; }

function ArchitecturePreview() { return <section id="architecture" className="border-y border-white/[.06] bg-white/[.015] py-24 sm:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 sm:px-8 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-semibold tracking-[.16em] text-violet-400">ARCHITECTURE, UNFOLDED</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-4xl">See the system behind the files.</h2><p className="mt-5 max-w-lg leading-7 text-zinc-400">GitLens turns a directory tree into a map your whole team can reason about. Follow connections, identify boundaries, and find the real owner of a behavior.</p><ul className="mt-7 space-y-3 text-sm text-zinc-300">{["Explore modules through the lens of responsibility", "Trace data flow between your services", "Spot tightly coupled areas before they slow you down"].map((item) => <li key={item} className="flex gap-3"><Check className="mt-0.5 size-4 shrink-0 text-emerald-400" />{item}</li>)}</ul></div><div className="rounded-2xl border border-white/[.08] bg-zinc-900/70 p-5 shadow-glow"><div className="relative h-72 overflow-hidden rounded-xl bg-[radial-gradient(circle_at_center,rgba(124,58,237,.13),transparent_60%)]"><GraphNode title="App shell" className="left-[37%] top-7" /><GraphNode title="Auth" className="left-[7%] top-[44%]" /><GraphNode title="Repository" className="left-[37%] top-[44%]" active /><GraphNode title="Dashboard" className="right-[7%] top-[44%]" /><GraphNode title="Database" className="left-[37%] bottom-6" /><svg className="absolute inset-0 h-full w-full" aria-hidden="true"><line x1="48%" y1="24%" x2="18%" y2="49%" stroke="rgba(167,139,250,.35)"/><line x1="48%" y1="24%" x2="48%" y2="49%" stroke="rgba(167,139,250,.35)"/><line x1="48%" y1="24%" x2="79%" y2="49%" stroke="rgba(167,139,250,.35)"/><line x1="48%" y1="57%" x2="48%" y2="78%" stroke="rgba(167,139,250,.35)"/></svg></div></div></div></section>; }
function GraphNode({ title, className, active = false }: { title: string; className: string; active?: boolean }) { return <motion.div whileHover={{ scale: 1.04 }} className={`absolute z-10 rounded-lg border px-3 py-2 text-xs shadow-lg ${active ? "border-violet-400/50 bg-violet-500/20 text-violet-100" : "border-white/[.1] bg-zinc-900 text-zinc-300"} ${className}`}>{title}</motion.div>; }

function DemoPreview() { return <section id="demo" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><div className="grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div className="order-2 lg:order-1 rounded-2xl border border-white/[.08] bg-zinc-900/60 p-3 shadow-glow"><div className="rounded-xl border border-white/[.06] bg-zinc-950 p-5 sm:p-6"><div className="flex items-center gap-2 text-xs text-zinc-500"><span className="grid size-6 place-items-center rounded-md bg-violet-400/10 text-violet-300"><BrainCircuit className="size-3.5" /></span> Ask GitLens</div><div className="mt-5 rounded-xl border border-violet-400/20 bg-violet-400/[.06] p-4 text-sm text-zinc-200">Where does checkout state get persisted?</div><div className="mt-3 rounded-xl bg-white/[.04] p-4 text-sm leading-6 text-zinc-400">Checkout state is managed by <span className="text-violet-300">CheckoutSession</span> and persisted through the order service. The session is created in the API route, then passed to the payment adapter before the final write.</div><div className="mt-4 flex gap-2"><span className="rounded-md bg-white/[.05] px-2 py-1 text-[11px] text-zinc-500">app/api/checkout</span><span className="rounded-md bg-white/[.05] px-2 py-1 text-[11px] text-zinc-500">services/orders</span></div></div></div><div className="order-1 lg:order-2"><p className="text-xs font-semibold tracking-[.16em] text-violet-400">A BETTER FIRST DAY</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Ask questions. Get real context.</h2><p className="mt-5 leading-7 text-zinc-400">From “where does this live?” to “what breaks if I change this?”, GitLens gives you direct, source-aware answers rather than another vague chatbot conversation.</p><Button asChild variant="outline" className="mt-7"><a href="#top">Watch the walkthrough <ArrowRight className="size-4" /></a></Button></div></div></section>; }

function Faq() { const [open, setOpen] = useState(0); return <section id="faq" className="border-t border-white/[.06] py-24 sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-semibold tracking-[.16em] text-violet-400">QUESTIONS, ANSWERED</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Everything you need to know.</h2></div><div className="divide-y divide-white/[.08] border-y border-white/[.08]">{faqs.map((faq, index) => <div key={faq.question}><button onClick={() => setOpen(open === index ? -1 : index)} className="flex w-full items-center justify-between gap-5 py-5 text-left text-sm font-medium text-zinc-100"><span>{faq.question}</span><ChevronDown className={`size-4 shrink-0 text-zinc-500 transition-transform ${open === index ? "rotate-180" : ""}`} /></button>{open === index && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} className="pb-5 text-sm leading-6 text-zinc-400">{faq.answer}</motion.p>}</div>)}</div></div></section>; }
function Footer() { return <footer className="border-t border-white/[.06] bg-white/[.015]"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 sm:flex-row sm:items-center sm:justify-between sm:px-8"><a href="#top" className="flex items-center gap-2 font-semibold tracking-tight text-white"><span className="grid size-7 place-items-center rounded-md bg-violet-500"><GitBranch className="size-3.5" /></span>GitLens AI</a><div className="flex gap-5 text-xs text-zinc-500"><a className="hover:text-zinc-300" href="#features">Product</a><a className="hover:text-zinc-300" href="#faq">FAQ</a><a className="hover:text-zinc-300" href="mailto:hello@gitlens.ai">Contact</a></div><div className="space-y-1 text-right text-xs text-zinc-500"><p>Team Zinc</p><p>MD Karaamathullah Sheriff - Founder</p><p>Sri Sai Vatsan - Co Founder</p></div><p className="text-xs text-zinc-600">© 2026 GitLens AI</p></div></footer>; }
