"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowUp, FileWarning, LoaderCircle, ShieldAlert, Sparkles } from "lucide-react";

import type { ChangeImpact } from "@/types/repository";

export function ChangeImpactSimulator({ repositoryId }: { repositoryId: string }) {
  const [query, setQuery] = useState("What happens if I rename UserService?"); const [impact, setImpact] = useState<ChangeImpact | null>(null); const [history, setHistory] = useState<ChangeImpact[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch(`/api/repositories/${repositoryId}/impact`).then((response) => response.ok ? response.json() : []).then(setHistory).catch(() => undefined); }, [repositoryId]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!query.trim()) return; setLoading(true); setError(null); try { const response = await fetch(`/api/repositories/${repositoryId}/impact`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setImpact(data); setHistory((current) => [data, ...current.filter((item) => item.createdAt !== data.createdAt)]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to simulate the change."); } finally { setLoading(false); } }
  return <section className="grid gap-5 xl:grid-cols-[1fr_300px]"><div><div className="rounded-2xl border border-white/[.08] bg-zinc-900/50 p-5 sm:p-6"><p className="text-xs font-semibold tracking-[.14em] text-violet-400">CHANGE IMPACT SIMULATOR</p><h2 className="mt-3 text-xl font-semibold text-white">Model the blast radius before you ship.</h2><p className="mt-2 text-sm text-zinc-400">Describe a change in plain English. GitLens traces the repository graph and explains the risk.</p><form onSubmit={submit} className="mt-6 flex gap-2 rounded-xl border border-white/[.1] bg-zinc-950 p-2"><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent px-2 text-sm text-white outline-none placeholder:text-zinc-600" placeholder="What happens if I rename UserService?"/><button disabled={loading} className="grid size-9 place-items-center rounded-lg bg-violet-500 text-white disabled:opacity-50">{loading ? <LoaderCircle className="size-4 animate-spin"/> : <ArrowUp className="size-4"/>}</button></form>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}</div>{impact && <ImpactResult impact={impact}/>}</div><aside className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-xs font-semibold tracking-[.14em] text-violet-400">SIMULATION HISTORY</p><div className="mt-4 space-y-2">{history.length ? history.map((item) => <button key={item.createdAt} onClick={() => { setQuery(item.query); setImpact(item); }} className="w-full rounded-lg border border-white/[.06] bg-zinc-950/50 p-3 text-left transition hover:border-violet-400/30"><p className="truncate text-xs text-zinc-300">{item.query}</p><p className="mt-1 text-[10px] text-zinc-600">Risk {item.riskScore} · {item.estimatedEffort} effort</p></button>) : <p className="mt-4 text-sm leading-6 text-zinc-500">Your simulations will appear here.</p>}</div></aside></section>;
}
function ImpactResult({ impact }: { impact: ChangeImpact }) { return <div className="mt-5 rounded-2xl border border-white/[.08] bg-white/[.025] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.14em] text-violet-400">IMPACT ASSESSMENT</p><h3 className="mt-2 text-lg font-semibold text-white">{impact.target ?? "Repository change"}</h3></div><div className={`rounded-xl border px-3 py-2 text-center ${impact.riskScore > 65 ? "border-red-400/25 bg-red-400/10" : impact.riskScore > 35 ? "border-amber-400/25 bg-amber-400/10" : "border-emerald-400/25 bg-emerald-400/10"}`}><p className="text-lg font-semibold text-white">{impact.riskScore}</p><p className="text-[10px] uppercase tracking-wide text-zinc-400">Risk score</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Affected files" value={impact.affectedFiles.length}/><Metric label="Breaking APIs" value={impact.breakingApis.length}/><Metric label="Confidence" value={`${impact.confidence}%`}/></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><DetailList title="Affected files" items={impact.affectedFiles}/><DetailList title="Tests required" items={impact.testsRequired}/></div><div className="mt-6 rounded-xl border border-violet-400/15 bg-violet-400/[.06] p-4"><p className="flex items-center gap-2 text-xs font-semibold text-violet-200"><Sparkles className="size-3.5"/> Reasoning</p><ul className="mt-3 space-y-2 text-sm leading-6 text-zinc-400">{impact.reasoning.map((item) => <li key={item}>{item}</li>)}</ul></div></div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-white/[.06] bg-zinc-950/70 p-3"><p className="text-xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-zinc-500">{label}</p></div>; }
function DetailList({ title, items }: { title: string; items: string[] }) { return <div><p className="mb-2 flex items-center gap-2 text-xs font-medium text-zinc-500"><FileWarning className="size-3.5 text-amber-400"/>{title}</p>{items.length ? <div className="space-y-1.5">{items.slice(0, 8).map((item) => <p key={item} className="truncate rounded-md bg-zinc-950/70 px-2.5 py-1.5 font-mono text-[11px] text-zinc-400">{item}</p>)}</div> : <p className="text-sm text-zinc-600">No direct matches detected.</p>}</div>; }
