import { createHash } from "node:crypto";

import type { RepositoryContext, RepositoryDocumentation, RiskFinding } from "@/types/repository";

const LARGE_FILE_BYTES = 75_000;
const securityPatterns: Array<[RegExp, string, string]> = [[/sk-[a-zA-Z0-9_-]{16,}/, "Possible API key committed to source", "Move secrets into environment variables and rotate any exposed credential."], [/(?:password|secret|token)\s*[:=]\s*["'][^"']{5,}/i, "Hard-coded credential-like value", "Load credentials from validated server-side environment variables."], [/dangerouslySetInnerHTML|eval\s*\(|new Function\s*\(/, "Unsafe dynamic execution or rendering", "Avoid dynamic execution and sanitize untrusted HTML before rendering."]];

function finding(partial: Omit<RiskFinding, "id">): RiskFinding { return { id: createHash("sha1").update(`${partial.category}:${partial.title}:${partial.files.join("|")}`).digest("hex").slice(0, 10), ...partial }; }

export function analyzeRepositoryRisks(context: RepositoryContext): RiskFinding[] {
  const results: RiskFinding[] = []; const inbound = new Set(context.analysis.dependencies.map((edge) => edge.target)); const duplicateBlocks = new Map<string, string[]>();
  for (const file of context.files) {
    if (file.size > LARGE_FILE_BYTES) results.push(finding({ category: "large-file", severity: file.size > 180_000 ? "high" : "medium", title: "Large source file", description: `${file.path} is ${(file.size / 1024).toFixed(0)} KB and may be difficult to maintain.`, files: [file.path], recommendation: "Split cohesive concerns into smaller modules with focused interfaces." }));
    if (!inbound.has(file.path) && !/(^|\/)(index|main|app|page|layout|route|server)\.[jt]sx?$/i.test(file.path) && !/test|spec|\.d\.ts/.test(file.path)) results.push(finding({ category: "dead-code", severity: "low", title: "Potentially unused module", description: "No analyzed local import references this module.", files: [file.path], recommendation: "Confirm it is not loaded dynamically, then remove it or add an explicit reference." }));
    const source = file.preview ?? "";
    for (const [pattern, title, recommendation] of securityPatterns) if (pattern.test(source)) results.push(finding({ category: "security", severity: "high", title, description: `A security-sensitive pattern was detected in ${file.path}.`, files: [file.path], recommendation }));
    if (/(^|\/)(api|routes?|controllers?)(\/|$)/i.test(file.path) && !/(zod|joi|yup|safeParse|parse\(|validate)/i.test(source)) results.push(finding({ category: "validation", severity: "medium", title: "API input validation not detected", description: "This API-facing file has no recognized validation pattern in its analyzed source.", files: [file.path], recommendation: "Validate request data at the boundary with a schema before using it." }));
    if (/(async |await |fetch\(|axios\.)/.test(source) && !/(try\s*\{|\.catch\(|error\s*=>|catch\s*\()/.test(source)) results.push(finding({ category: "error-handling", severity: "medium", title: "Missing visible error handling", description: "Async work appears without a nearby error-handling pattern.", files: [file.path], recommendation: "Handle expected failures and return actionable errors to the caller." }));
    const blocks = source.match(/(?:function|const|export\s+function)[\s\S]{0,800}/g) ?? []; for (const block of blocks) { if (block.length < 160) continue; const key = createHash("sha1").update(block.replace(/\s+/g, " ").replace(/[A-Za-z_$][\w$]*/g, "id")).digest("hex"); duplicateBlocks.set(key, [...(duplicateBlocks.get(key) ?? []), file.path]); }
  }
  for (const files of duplicateBlocks.values()) if (new Set(files).size > 1) results.push(finding({ category: "duplicate-logic", severity: "medium", title: "Similar implementation pattern", description: "Comparable function-sized logic appears in multiple files.", files: [...new Set(files)].slice(0, 5), recommendation: "Extract shared behavior only if the duplication represents the same business rule." }));
  return results.sort((a, b) => ({ critical: 0, high: 1, medium: 2, low: 3 }[a.severity] - { critical: 0, high: 1, medium: 2, low: 3 }[b.severity]));
}

export function generateRepositoryDocumentation(context: RepositoryContext, risks: RiskFinding[]): RepositoryDocumentation {
  const modules = context.analysis.modules.map((module) => `- **${module.name}** (${module.kind}): ${module.files.slice(0, 5).map((file) => `\`${file}\``).join(", ")}`).join("\n") || "- No high-level modules were classified.";
  const apiFiles = context.files.filter((file) => /(^|\/)(api|routes?|controllers?)(\/|$)/i.test(file.path)).map((file) => file.path);
  const folders = context.analysis.fileTree.reduce((groups, path) => { const folder = path.split("/").slice(0, -1).join("/") || "/"; groups.set(folder, [...(groups.get(folder) ?? []), path]); return groups; }, new Map<string, string[]>());
  return { readme: `# ${context.repository.name}\n\n${context.analysis.summary}\n\n## Stack\n\n${context.analysis.frameworks.map((framework) => `- ${framework}`).join("\n") || "- Not detected"}\n\n## Repository map\n\n${modules}\n\n## Quality snapshot\n\n${risks.length} automated findings were identified. Review them before production deployment.`, architecture: `# Architecture — ${context.repository.name}\n\n## Overview\n\n${context.analysis.summary}\n\n## Domains\n\n${modules}\n\n## Relationships\n\n${context.analysis.architecture.edges.map((edge) => `- **${edge.source}** → **${edge.target}** — ${edge.relationship}`).join("\n") || "No cross-domain relationships were detected."}\n\n## Dependency health\n\n- Local dependencies: ${context.analysis.dependencies.length}\n- Circular dependency groups: ${context.analysis.circularDependencies.length}`, folders: `# Folder guide — ${context.repository.name}\n\n${Array.from(folders.entries()).map(([folder, files]) => `## \`${folder}\`\n\n${files.slice(0, 12).map((file) => `- \`${file.split("/").at(-1)}\``).join("\n")}`).join("\n\n")}`, api: `# API guide — ${context.repository.name}\n\n${apiFiles.length ? apiFiles.map((file) => `## \`${file}\`\n\nReview the source for method, request schema, and response contract details.`).join("\n\n") : "No conventional API routes or controller folders were detected."}` };
}
